### ISSUE TITLE
policejob Ajout grade sheriff dans le job police

### ISSUE THREAD

**Issue by RedAlex** [RedAlex/FamilyCrewToDo#5]

**Comment by TonyLorenzo** [comment]
Les vehicule seront envoyer en prive.
Deux Grades:
Sheriff Superviseur
Sheriff Officier

Vehicule Par Grade:

Superviseur: Ram et Silverado
Officer: Silverado

Tenue:

T-Shirt1: 38
T-Shirt2: 0
Torse1: 26
Torse2: 4
Bras1: 11
Bras2: 0
Jambes1: 86
Jambes2: 14
Chaussures1: 38
Chaussures2: 1
Masque1: 121
Masque2: 0
Gilet Pare-Balle1: 4
Gilet Pare-Balle2: 2
Chaine1: 1
Chaine2: 0
Casque1: 13
Casque2: 5

Gros Merci Garcio fait moi signe si ta besoin de quoi que se sois!!

**Comment by RedAlex** [comment]
Refuser par Max
